# Generated by Django 4.2.11 on 2026-07-29 05:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('name_nepali', models.CharField(blank=True, max_length=255)),
                ('category', models.CharField(choices=[('nepali_staple', 'Nepali Staple'), ('nepali_snack', 'Nepali Snack'), ('nepali_bread', 'Nepali Bread'), ('nepali_curry', 'Nepali Curry'), ('nepali_vegetable', 'Nepali Vegetable'), ('nepali_meat', 'Nepali Meat'), ('nepali_sweet', 'Nepali Sweet'), ('nepali_beverage', 'Nepali Beverage'), ('nepali_pickle', 'Nepali Pickle'), ('grain', 'Grain'), ('vegetable', 'Vegetable'), ('fruit', 'Fruit'), ('dairy', 'Dairy'), ('protein', 'Protein'), ('fat_oil', 'Fat/Oil'), ('beverage', 'Beverage'), ('snack', 'Snack'), ('international', 'International')], max_length=50)),
                ('calories', models.FloatField()),
                ('protein', models.FloatField()),
                ('carbohydrates', models.FloatField()),
                ('fat', models.FloatField()),
                ('fiber', models.FloatField(default=0)),
                ('sugar', models.FloatField(default=0)),
                ('sodium', models.FloatField(default=0)),
                ('is_vegetarian', models.BooleanField(default=False)),
                ('is_vegan', models.BooleanField(default=False)),
                ('is_gluten_free', models.BooleanField(default=False)),
                ('contains_nuts', models.BooleanField(default=False)),
                ('contains_dairy', models.BooleanField(default=False)),
                ('contains_gluten', models.BooleanField(default=False)),
                ('contains_egg', models.BooleanField(default=False)),
                ('is_nepali', models.BooleanField(default=False)),
                ('data_source', models.CharField(blank=True, max_length=255)),
                ('serving_size_g', models.FloatField(default=100)),
            ],
        ),
        migrations.CreateModel(
            name='MealLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_g', models.FloatField()),
                ('meal_type', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('snack', 'Snack'), ('dinner', 'Dinner')], max_length=20)),
                ('logged_at', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nutrition.food')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
