# Generated by Django 4.2.11 on 2026-08-15 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recommendationhistory',
            options={'ordering': ['-recommended_at']},
        ),
        migrations.AddField(
            model_name='recommendationhistory',
            name='feedback',
            field=models.CharField(blank=True, choices=[('liked', 'Liked'), ('disliked', 'Disliked'), ('neutral', 'Neutral')], db_index=True, max_length=10, null=True),
        ),
    ]
